version: '3'
services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=centralachat
    volumes:
      - CentralAchatVolume:/var/lib/mysql
    ports:
      - "3306:3306"

  eureka:
    build:
      context: ..\EurekaServer
      dockerfile: DockerFileEureka
    image: eureka-image
    restart: always
    container_name: eureka
    ports:
      - "8761:8761"

  gateway:
    build:
      context: ..\API_Gateway
      dockerfile: DockerFileGateway
    container_name: gateway
    image: api-gateway-image
    restart: always
    depends_on:
      - eureka
    ports:
      - "8083:8083"

    environment:
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
      - eureka.instance.preferIpAddress=true
      - eureka.instance.leaseRenewalIntervalInSeconds=10
      - eureka.instance.leaseExpirationDurationInSeconds=30
      - spring.cloud.gateway.routes[0].id=forum
      - spring.cloud.gateway.routes[0].uri=http://forum:9001
      - spring.cloud.gateway.routes[0].predicates[0]=Path=/forum/**
      #EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://host.docker.internal:8761/eureka
      #jdbc:mysql://mysqldb/host.docker.internal/centralachat?autoReconnect=true&useSSL=false


  forum:
    build:
      context: ../ForumMs
      dockerfile: DockerFileForum
    container_name: forum
    image: forum-image
    restart: always
    ports:
      - "9001:9001"
    depends_on:
      - mysql
      - eureka
    environment:
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
      - eureka.instance.preferIpAddress=true
      - eureka.instance.leaseRenewalIntervalInSeconds=10
      - eureka.instance.leaseExpirationDurationInSeconds=30
      - spring.datasource.url=jdbc:mysql://mysql:3306/centralachat?createDatabaseIfNotExists=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
      - spring.datasource.driver-class-name=com.mysql.jdbc.Driver
volumes:
  CentralAchatVolume: